replicas: 1
podAnnotations: {}
podLabels: {}
vpa:
  enabled: false
  mode: Auto

image:
  repository: ghcr.io/breuerfelix/medusa-operator/operator
  tag: latest

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 512Mi

