---
apiVersion: app.medusa.fbr.ai/v1
kind: Medusa
metadata:
  namespace: medusa
  name: testing-user
spec:
  backend:
    image: ghcr.io/breuerfelix/medusa/backend:latest
    domain: medusa.fbr.ai
    redisURL: "redis://redis-master.redis:6379?ConnectTimeout=5000&password=aejfioj388749q41aasd&IdleTimeOutSecs=180&channelPrefix=testing-user"
  admin:
    image: ghcr.io/breuerfelix/medusa/admin:latest
    domain: medusa-admin.fbr.ai
